<a href="https://colab.research.google.com/github/DivyaDharshini2293/Machine-learning/blob/main/BYTS_RandomForest_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df.Education.value_counts()

Graduate        480
Not Graduate    134
Name: Education, dtype: int64

In [ ]:
df.Education.nunique()

2

In [ ]:
for i in df:
  print(i)
  print(df[i].value_counts())

Loan_ID
LP001002    1
LP002328    1
LP002305    1
LP002308    1
LP002314    1
           ..
LP001692    1
LP001693    1
LP001698    1
LP001699    1
LP002990    1
Name: Loan_ID, Length: 614, dtype: int64
Gender
Male      489
Female    112
Name: Gender, dtype: int64
Married
Yes    398
No     213
Name: Married, dtype: int64
Dependents
0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64
Education
Graduate        480
Not Graduate    134
Name: Education, dtype: int64
Self_Employed
No     500
Yes     82
Name: Self_Employed, dtype: int64
ApplicantIncome
2500    9
4583    6
6000    6
2600    6
3333    5
       ..
3244    1
4408    1
3917    1
3992    1
7583    1
Name: ApplicantIncome, Length: 505, dtype: int64
CoapplicantIncome
0.0       273
2500.0      5
2083.0      5
1666.0      5
2250.0      3
         ...
2791.0      1
1010.0      1
1695.0      1
2598.0      1
240.0       1
Name: CoapplicantIncome, Length: 287, dtype: int64
LoanAmount
120.0    20
110.0    17
100.0    15
160.0    12
187.0    12
         ..
240.0     1
214.0     1
59.0      1
166.0     1
253.0     1
Name: LoanAmount, Length: 203, dtype: int64
Loan_Amount_Term
360.0    512
180.0     44
480.0     15
300.0     13
240.0      4
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: Loan_Amount_Term, dtype: int64
Credit_History
1.0    475
0.0     89
Name: Credit_History, dtype: int64
Property_Area
Semiurban    233
Urban        202
Rural        179
Name: Property_Area, dtype: int64
Loan_Status
Y    422
N    192
Name: Loan_Status, dtype: int64

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
for i in df:
  if(df[i].dtype==object):
    print(i)
    df[i]=df[i].fillna(df[i].mode()[0])

Loan_ID
Gender
Married
Dependents
Education
Self_Employed
Property_Area
Loan_Status

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
for i in ['LoanAmount','Loan_Amount_Term','Credit_History']:
  df[i]=df[i].fillna(df[i].mean())

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
#df['Gender']=df['Gender].map('Male':1,'Female':0)

In [ ]:
#One Hot Encoding
df=pd.get_dummies(df,columns=['Gender','Loan_ID'])
#df=pd.get_dummies(df,columns=['Gender'])

In [ ]:
df

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,...,Loan_ID_LP002959,Loan_ID_LP002960,Loan_ID_LP002961,Loan_ID_LP002964,Loan_ID_LP002974,Loan_ID_LP002978,Loan_ID_LP002979,Loan_ID_LP002983,Loan_ID_LP002984,Loan_ID_LP002990
0,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,...,0,0,0,0,0,0,0,0,0,0
1,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,...,0,0,0,0,0,0,0,0,0,0
2,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,...,0,0,0,0,0,0,0,0,0,0
3,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,...,0,0,0,0,0,0,0,0,0,0
4,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,...,0,0,0,0,0,1,0,0,0,0
610,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,...,0,0,0,0,0,0,1,0,0,0
611,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,...,0,0,0,0,0,0,0,1,0,0
612,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,...,0,0,0,0,0,0,0,0,1,0
613,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,...,0,0,0,0,0,0,0,0,0,1

**Encoding**

In [ ]:
col=['Property_Area','Loan_Status','Self_Employed','Married','Education','Dependents']

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
for i in col:
  df[i]=lb.fit_transform(df[i])

In [ ]:
df

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,...,Loan_ID_LP002959,Loan_ID_LP002960,Loan_ID_LP002961,Loan_ID_LP002964,Loan_ID_LP002974,Loan_ID_LP002978,Loan_ID_LP002979,Loan_ID_LP002983,Loan_ID_LP002984,Loan_ID_LP002990
0,0,0,0,0,5849,0.0,146.412162,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,4583,1508.0,128.000000,360.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,1,3000,0.0,66.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,2583,2358.0,120.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,6000,0.0,141.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,2900,0.0,71.000000,360.0,1.0,0,...,0,0,0,0,0,1,0,0,0,0
610,1,3,0,0,4106,0.0,40.000000,180.0,1.0,0,...,0,0,0,0,0,0,1,0,0,0
611,1,1,0,0,8072,240.0,253.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,1,0,0
612,1,2,0,0,7583,0.0,187.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,1,0
613,0,0,0,1,4583,0.0,133.000000,360.0,0.0,1,...,0,0,0,0,0,0,0,0,0,1

**Handle NULL**

In [ ]:
df.isnull().sum()

Married             0
Dependents          0
Education           0
Self_Employed       0
ApplicantIncome     0
                   ..
Loan_ID_LP002978    0
Loan_ID_LP002979    0
Loan_ID_LP002983    0
Loan_ID_LP002984    0
Loan_ID_LP002990    0
Length: 627, dtype: int64

In [ ]:
df=df.fillna(method='ffill')

In [ ]:
df.isnull().sum()

Married             0
Dependents          0
Education           0
Self_Employed       0
ApplicantIncome     0
                   ..
Loan_ID_LP002978    0
Loan_ID_LP002979    0
Loan_ID_LP002983    0
Loan_ID_LP002984    0
Loan_ID_LP002990    0
Length: 627, dtype: int64

In [ ]:
df=df.fillna(0)

In [ ]:
df.isnull().sum()

Married             0
Dependents          0
Education           0
Self_Employed       0
ApplicantIncome     0
                   ..
Loan_ID_LP002978    0
Loan_ID_LP002979    0
Loan_ID_LP002983    0
Loan_ID_LP002984    0
Loan_ID_LP002990    0
Length: 627, dtype: int64

**Check Duplicates**

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status, Gender_Female, Gender_Male, Loan_ID_LP001002, Loan_ID_LP001003, Loan_ID_LP001005, Loan_ID_LP001006, Loan_ID_LP001008, Loan_ID_LP001011, Loan_ID_LP001013, Loan_ID_LP001014, Loan_ID_LP001018, Loan_ID_LP001020, Loan_ID_LP001024, Loan_ID_LP001027, Loan_ID_LP001028, Loan_ID_LP001029, Loan_ID_LP001030, Loan_ID_LP001032, Loan_ID_LP001034, Loan_ID_LP001036, Loan_ID_LP001038, Loan_ID_LP001041, Loan_ID_LP001043, Loan_ID_LP001046, Loan_ID_LP001047, Loan_ID_LP001050, Loan_ID_LP001052, Loan_ID_LP001066, Loan_ID_LP001068, Loan_ID_LP001073, Loan_ID_LP001086, Loan_ID_LP001087, Loan_ID_LP001091, Loan_ID_LP001095, Loan_ID_LP001097, Loan_ID_LP001098, Loan_ID_LP001100, Loan_ID_LP001106, Loan_ID_LP001109, Loan_ID_LP001112, Loan_ID_LP001114, Loan_ID_LP001116, Loan_ID_LP001119, Loan_ID_LP001120, Loan_ID_LP001123, Loan_ID_LP001131, Loan_ID_LP001136, Loan_ID_LP001137, Loan_ID_LP001138, Loan_ID_LP001144, Loan_ID_LP001146, Loan_ID_LP001151, Loan_ID_LP001155, Loan_ID_LP001157, Loan_ID_LP001164, Loan_ID_LP001179, Loan_ID_LP001186, Loan_ID_LP001194, Loan_ID_LP001195, Loan_ID_LP001197, Loan_ID_LP001198, Loan_ID_LP001199, Loan_ID_LP001205, Loan_ID_LP001206, Loan_ID_LP001207, Loan_ID_LP001213, Loan_ID_LP001222, Loan_ID_LP001225, Loan_ID_LP001228, Loan_ID_LP001233, Loan_ID_LP001238, Loan_ID_LP001241, Loan_ID_LP001243, Loan_ID_LP001245, Loan_ID_LP001248, Loan_ID_LP001250, Loan_ID_LP001253, Loan_ID_LP001255, Loan_ID_LP001256, Loan_ID_LP001259, Loan_ID_LP001263, Loan_ID_LP001264, Loan_ID_LP001265, Loan_ID_LP001266, Loan_ID_LP001267, Loan_ID_LP001273, Loan_ID_LP001275, Loan_ID_LP001279, Loan_ID_LP001280, ...]
Index: []

[0 rows x 627 columns]

In [ ]:
x=df.drop(["Loan_Status"],axis=1)
y=df['Loan_Status']

In [ ]:
x.head()

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,...,Loan_ID_LP002959,Loan_ID_LP002960,Loan_ID_LP002961,Loan_ID_LP002964,Loan_ID_LP002974,Loan_ID_LP002978,Loan_ID_LP002979,Loan_ID_LP002983,Loan_ID_LP002984,Loan_ID_LP002990
0,0,0,0,0,5849,0.0,146.412162,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,4583,1508.0,128.000000,360.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,1,3000,0.0,66.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,2583,2358.0,120.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,6000,0.0,141.000000,360.0,1.0,2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape

(491, 626)

In [ ]:
x_test.shape

(123, 626)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

x_test=sc.fit_transform(x_test)

#RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(criterion="entropy",random_state=42)

In [ ]:
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [ ]:
y_pred=rf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)

0.7886178861788617

In [ ]:
confusion_matrix(y_pred,y_test)

array([[18,  1],
       [25, 79]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.42      0.95      0.58        19
           1       0.99      0.76      0.86       104

    accuracy                           0.79       123
   macro avg       0.70      0.85      0.72       123
weighted avg       0.90      0.79      0.82       123

#Gradient Boosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [ ]:
y_pred1=gb.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred1,y_test)

0.7886178861788617

In [ ]:
confusion_matrix(y_pred1,y_test)

array([[19,  2],
       [24, 78]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.42      0.95      0.58        19
           1       0.99      0.76      0.86       104

    accuracy                           0.79       123
   macro avg       0.70      0.85      0.72       123
weighted avg       0.90      0.79      0.82       123

#AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ad=AdaBoostClassifier()

In [ ]:
ad.fit(x_train,y_train)

AdaBoostClassifier()

In [ ]:
y_pred2=ad.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred1,y_test)

0.7886178861788617

In [ ]:
confusion_matrix(y_pred1,y_test)

array([[19,  2],
       [24, 78]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.42      0.95      0.58        19
           1       0.99      0.76      0.86       104

    accuracy                           0.79       123
   macro avg       0.70      0.85      0.72       123
weighted avg       0.90      0.79      0.82       123